version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: risk
      POSTGRES_DB: riskscan
    ports: [ "5432:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5

  api:
    build: .
    command: bunx turbo run --filter=apps/api start
    environment:
      DATABASE_URL: postgres://postgres:risk@db:5432/riskscan
      PORT: 4000
    ports: [ "4000:4000" ]
    depends_on:
      db:
        condition: service_healthy
