name: Nightly
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-node-bun
        with:
          node-version: '22'
          bun-version: 'latest'
      - run: bun install --frozen-lockfile
      - run: bun run test:ci
      - run: echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
